# Generated by Django 6.0.1 on 2026-05-23 08:37

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=orders.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('subtotal', models.IntegerField(default=0)),
                ('vat', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('shipping_address', models.JSONField(default=dict)),
                ('payment_method', models.CharField(default='COD', max_length=50)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
