import { Product } from '@/types';

export const CATEGORIES = [
  'Vegetables',
  'Fruits',
  'Grains',
  'Dairy',
  'Organic',
  'Seeds',
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Tomatoes',
    description: 'Fresh, juicy organic tomatoes grown without pesticides. Locally sourced from Nepal | availability may vary by region.',
    price: 120,
    category: 'Vegetables',
    image: '/images/tomatoes.jpg',
    farmer: 'Dhading, Bagmati Province',
    farmerId: 'f1',
    rating: 4.8,
    reviews: 234,
    inStock: true,
  },
  {
    id: '2',
    name: 'Fresh Carrots',
    description: 'Crunchy orange carrots, perfect for salads and cooking. Available from farms in Nepal | local sourcing may vary by region.',
    price: 95,
    category: 'Vegetables',
    image: '/images/carrots.jpg',
    farmer: 'Sindhupalchok, Bagmati Province',
    farmerId: 'f2',
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '3',
    name: 'Apple Variety Pack',
    description: 'Mix of Red, Green, and Golden Delicious apples. Fresh from Nepal\'s hill regions | seasonal availability applies.',
    price: 280,
    category: 'Fruits',
    image: '/images/apples.jpg',
    farmer: 'Mustang, Gandaki Province',
    farmerId: 'f3',
    rating: 4.9,
    reviews: 412,
    inStock: true,
  },
  {
    id: '4',
    name: 'Organic Strawberries',
    description: 'Sweet, ripe strawberries picked fresh. Available in season from local farms in Nepal.',
    price: 450,
    category: 'Fruits',
    image: '/images/strawberries.jpg',
    farmer: 'Nuwakot, Bagmati Province',
    farmerId: 'f4',
    rating: 4.7,
    reviews: 356,
    inStock: true,
  },
  {
    id: '5',
    name: 'Whole Wheat Flour',
    description: 'Stone-ground whole wheat flour for baking and everyday cooking. Sourced from local grain producers in Nepal.',
    price: 85,
    category: 'Grains',
    image: '/images/wheat.jpg',
    farmer: 'Jumla, Karnali Province',
    farmerId: 'f5',
    rating: 4.5,
    reviews: 123,
    inStock: true,
  },
  {
    id: '6',
    name: 'Fresh Milk',
    description: 'Pure, fresh milk from healthy cows. Collected from dairy farms across Nepal | local sourcing may vary by region.',
    price: 110,
    category: 'Dairy',
    image: '/images/milk.jpg',
    farmer: 'Chitwan, Bagmati Province',
    farmerId: 'f6',
    rating: 4.8,
    reviews: 298,
    inStock: true,
  },
  {
    id: '7',
    name: 'Organic Spinach',
    description: 'Fresh organic spinach, great for smoothies and salads. Grown without chemicals from Nepal farms.',
    price: 60,
    category: 'Vegetables',
    image: '/images/spinach.jpg',
    farmer: 'Dhading, Bagmati Province',
    farmerId: 'f1',
    rating: 4.6,
    reviews: 167,
    inStock: true,
  },
  {
    id: '8',
    name: 'Fresh Broccoli',
    description: 'Crisp, green broccoli florets. Freshly harvested and available from farms in Nepal.',
    price: 140,
    category: 'Vegetables',
    image: '/images/broccoli.jpg',
    farmer: 'Sindhupalchok, Bagmati Province',
    farmerId: 'f2',
    rating: 4.7,
    reviews: 145,
    inStock: true,
  },
  {
    id: '9',
    name: 'Bananas (Bunch)',
    description: 'Golden ripe bananas, perfect for smoothies and snacks. Widely available across Nepal.',
    price: 120,
    category: 'Fruits',
    image: '/images/bananas.jpg',
    farmer: 'Chitwan, Bagmati Province',
    farmerId: 'f7',
    rating: 4.5,
    reviews: 201,
    inStock: true,
  },
  {
    id: '10',
    name: 'Cheese Block',
    description: 'Artisanal cheese made from fresh local milk. Crafted by dairy producers in Nepal.',
    price: 950,
    category: 'Dairy',
    image: '/images/cheese.jpg',
    farmer: 'Solukhumbu, Koshi Province',
    farmerId: 'f8',
    rating: 4.9,
    reviews: 89,
    inStock: true,
  },
  {
    id: '11',
    name: 'Lettuce Head',
    description: 'Crisp, tender lettuce leaves. Freshly grown and available from local farms in Nepal.',
    price: 75,
    category: 'Vegetables',
    image: '/images/lettuce.jpg',
    farmer: 'Kavrepalanchok, Bagmati Province',
    farmerId: 'f1',
    rating: 4.6,
    reviews: 112,
    inStock: true,
  },
  {
    id: '12',
    name: 'Pumpkins',
    description: 'Large, orange pumpkins for seasonal cooking. Commonly grown across Nepal\'s Terai and hill regions.',
    price: 50,
    category: 'Vegetables',
    image: '/images/pumpkin.jpg',
    farmer: 'Nawalparasi, Gandaki Province',
    farmerId: 'f9',
    rating: 4.7,
    reviews: 78,
    inStock: true,
  },
  {
    id: '13',
    name: 'Honey Jar',
    description: 'Pure, raw honey from local bees. Sourced from beekeepers across Nepal\'s mountain and hill regions.',
    price: 850,
    category: 'Organic',
    image: '/images/honey.jpg',
    farmer: 'Lamjung, Gandaki Province',
    farmerId: 'f10',
    rating: 4.9,
    reviews: 234,
    inStock: true,
  },
  {
    id: '14',
    name: 'Vegetable Seeds Pack',
    description: 'Quality vegetable seeds suited for home gardening in Nepal\'s climate. Good for kitchen gardens.',
    price: 45,
    category: 'Seeds',
    image: '/images/seeds.jpg',
    farmer: 'Bhaktapur, Bagmati Province',
    farmerId: 'f11',
    rating: 4.4,
    reviews: 56,
    inStock: true,
  },
  {
    id: '15',
    name: 'Fresh Peaches',
    description: 'Juicy, sweet peaches in season. Grown in Nepal\'s mid-hill regions | seasonal availability applies.',
    price: 180,
    category: 'Fruits',
    image: '/images/peaches.jpg',
    farmer: 'Palpa, Lumbini Province',
    farmerId: 'f3',
    rating: 4.8,
    reviews: 203,
    inStock: true,
  },
];