import { Product } from '@/types';

export const CATEGORIES = [
  'Vegetables',
  'Fruits',
  'Grains',
  'Dairy',
  'Organic',
  'Seeds',
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Tomatoes',
    description: 'Fresh, juicy organic tomatoes grown without pesticides',
    price: 4.99,
    category: 'Vegetables',
    image: '/images/tomatoes.jpg',
    farmer: 'Green Valley Farm',
    farmerId: 'f1',
    rating: 4.8,
    reviews: 234,
    inStock: true,
  },
  {
    id: '2',
    name: 'Fresh Carrots',
    description: 'Crunchy orange carrots, perfect for salads and cooking',
    price: 3.49,
    category: 'Vegetables',
    image: '/images/carrots.jpg',
    farmer: 'Sunrise Farm',
    farmerId: 'f2',
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '3',
    name: 'Apple Variety Pack',
    description: 'Mix of Red, Green, and Golden Delicious apples',
    price: 7.99,
    category: 'Fruits',
    image: '/images/apples.jpg',
    farmer: 'Orchard Hills',
    farmerId: 'f3',
    rating: 4.9,
    reviews: 412,
    inStock: true,
  },
  {
    id: '4',
    name: 'Organic Strawberries',
    description: 'Sweet, ripe strawberries picked fresh from our fields',
    price: 5.99,
    category: 'Fruits',
    image: '/images/strawberries.jpg',
    farmer: 'Berry Best Farm',
    farmerId: 'f4',
    rating: 4.7,
    reviews: 356,
    inStock: true,
  },
  {
    id: '5',
    name: 'Whole Wheat Flour',
    description: 'Stone-ground whole wheat flour for baking',
    price: 6.49,
    category: 'Grains',
    image: '/images/wheat.jpg',
    farmer: 'Golden Grain Mill',
    farmerId: 'f5',
    rating: 4.5,
    reviews: 123,
    inStock: true,
  },
  {
    id: '6',
    name: 'Fresh Milk',
    description: 'Pure, fresh milk from grass-fed cows',
    price: 3.99,
    category: 'Dairy',
    image: '/images/milk.jpg',
    farmer: 'Happy Cow Dairy',
    farmerId: 'f6',
    rating: 4.8,
    reviews: 298,
    inStock: true,
  },
  {
    id: '7',
    name: 'Organic Spinach',
    description: 'Fresh organic spinach, great for smoothies and salads',
    price: 2.99,
    category: 'Vegetables',
    image: '/images/spinach.jpg',
    farmer: 'Green Valley Farm',
    farmerId: 'f1',
    rating: 4.6,
    reviews: 167,
    inStock: true,
  },
  {
    id: '8',
    name: 'Fresh Broccoli',
    description: 'Crisp, green broccoli florets',
    price: 3.99,
    category: 'Vegetables',
    image: '/images/broccoli.jpg',
    farmer: 'Sunrise Farm',
    farmerId: 'f2',
    rating: 4.7,
    reviews: 145,
    inStock: true,
  },
  {
    id: '9',
    name: 'Bananas (Bunch)',
    description: 'Golden ripe bananas, perfect for smoothies and snacks',
    price: 2.49,
    category: 'Fruits',
    image: '/images/bananas.jpg',
    farmer: 'Tropical Haven Farm',
    farmerId: 'f7',
    rating: 4.5,
    reviews: 201,
    inStock: true,
  },
  {
    id: '10',
    name: 'Cheese Block',
    description: 'Artisanal cheese made from fresh milk',
    price: 12.99,
    category: 'Dairy',
    image: '/images/cheese.jpg',
    farmer: 'Artisan Dairy Co',
    farmerId: 'f8',
    rating: 4.9,
    reviews: 89,
    inStock: true,
  },
  {
    id: '11',
    name: 'Lettuce Head',
    description: 'Crisp, tender lettuce leaves',
    price: 2.49,
    category: 'Vegetables',
    image: '/images/lettuce.jpg',
    farmer: 'Green Valley Farm',
    farmerId: 'f1',
    rating: 4.6,
    reviews: 112,
    inStock: true,
  },
  {
    id: '12',
    name: 'Pumpkins',
    description: 'Large, orange pumpkins for fall and cooking',
    price: 8.99,
    category: 'Vegetables',
    image: '/images/pumpkin.jpg',
    farmer: 'Autumn Harvest Farm',
    farmerId: 'f9',
    rating: 4.7,
    reviews: 78,
    inStock: true,
  },
  {
    id: '13',
    name: 'Honey Jar',
    description: 'Pure, raw honey from local bees',
    price: 9.99,
    category: 'Organic',
    image: '/images/honey.jpg',
    farmer: 'Beehive Valley',
    farmerId: 'f10',
    rating: 4.9,
    reviews: 234,
    inStock: true,
  },
  {
    id: '14',
    name: 'Vegetable Seeds Pack',
    description: 'Premium vegetable seeds for home gardening',
    price: 5.49,
    category: 'Seeds',
    image: '/images/seeds.jpg',
    farmer: 'Seed Masters',
    farmerId: 'f11',
    rating: 4.4,
    reviews: 56,
    inStock: true,
  },
  {
    id: '15',
    name: 'Fresh Peaches',
    description: 'Juicy, sweet peaches in season',
    price: 4.99,
    category: 'Fruits',
    image: '/images/peaches.jpg',
    farmer: 'Orchard Hills',
    farmerId: 'f3',
    rating: 4.8,
    reviews: 203,
    inStock: true,
  },
];

export const MOCK_FARMERS = [
  {
    id: 'f1',
    name: 'Green Valley Farm',
    location: 'California',
    description: 'Family-owned organic farm specializing in fresh vegetables',
    avatar: '/images/farmer1.jpg',
    rating: 4.7,
    reviews: 512,
  },
  {
    id: 'f2',
    name: 'Sunrise Farm',
    location: 'Oregon',
    description: 'Sustainable farming practices for healthy produce',
    avatar: '/images/farmer2.jpg',
    rating: 4.6,
    reviews: 334,
  },
  {
    id: 'f3',
    name: 'Orchard Hills',
    location: 'Washington',
    description: 'Fruit orchard with decades of experience',
    avatar: '/images/farmer3.jpg',
    rating: 4.8,
    reviews: 615,
  },
];
