# Generated by Django 6.0.1 on 2026-05-23 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
